# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: attack_detector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'attack_detector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61ttack_detector.proto\x12\x0f\x61ttack_detector\"\x07\n\x05\x45mpty\"\x1f\n\x08\x41ttackId\x12\x13\n\x0b\x61ttack_uuid\x18\x01 \x01(\t\"{\n\x0b\x41ttackSpecs\x12,\n\tattack_id\x18\x01 \x01(\x0b\x32\x19.attack_detector.AttackId\x12\x1d\n\x15probability_threshold\x18\x02 \x01(\x02\x12\x1f\n\x17min_ml_confidence_level\x18\x03 \x01(\x02\x32\xca\x02\n\x0e\x41ttackDetector\x12I\n\x0f\x43onfigureAttack\x12\x1c.attack_detector.AttackSpecs\x1a\x16.attack_detector.Empty\"\x00\x12Q\n\x15ListConfiguredAttacks\x12\x16.attack_detector.Empty\x1a\x1c.attack_detector.AttackSpecs\"\x00\x30\x01\x12P\n\x13GetConfiguredAttack\x12\x19.attack_detector.AttackId\x1a\x1c.attack_detector.AttackSpecs\"\x00\x12H\n\x11\x44\x65\x63onfigureAttack\x12\x19.attack_detector.AttackId\x1a\x16.attack_detector.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attack_detector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=42
  _globals['_EMPTY']._serialized_end=49
  _globals['_ATTACKID']._serialized_start=51
  _globals['_ATTACKID']._serialized_end=82
  _globals['_ATTACKSPECS']._serialized_start=84
  _globals['_ATTACKSPECS']._serialized_end=207
  _globals['_ATTACKDETECTOR']._serialized_start=210
  _globals['_ATTACKDETECTOR']._serialized_end=540
# @@protoc_insertion_point(module_scope)
