# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: traffic_sniffer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'traffic_sniffer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15traffic_sniffer.proto\x12\x12traffic.sniffer.v1\"\x07\n\x05\x45mpty\"A\n\rConfiguration\x12\x18\n\x10source_interface\x18\x01 \x01(\t\x12\x16\n\x0e\x63\x61pture_filter\x18\x02 \x01(\t\"H\n\x06Status\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.traffic.sniffer.v1.StatusEnum\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t*H\n\nStatusEnum\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n\x0eSTATUS_STOPPED\x10\x01\x12\x12\n\x0eSTATUS_RUNNING\x10\x02\x32\xfb\x02\n\x0eTrafficSniffer\x12S\n\tConfigure\x12!.traffic.sniffer.v1.Configuration\x1a!.traffic.sniffer.v1.Configuration\"\x00\x12K\n\tGetConfig\x12\x19.traffic.sniffer.v1.Empty\x1a!.traffic.sniffer.v1.Configuration\"\x00\x12@\n\x05Start\x12\x19.traffic.sniffer.v1.Empty\x1a\x1a.traffic.sniffer.v1.Status\"\x00\x12?\n\x04Stop\x12\x19.traffic.sniffer.v1.Empty\x1a\x1a.traffic.sniffer.v1.Status\"\x00\x12\x44\n\tGetStatus\x12\x19.traffic.sniffer.v1.Empty\x1a\x1a.traffic.sniffer.v1.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'traffic_sniffer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSENUM']._serialized_start=195
  _globals['_STATUSENUM']._serialized_end=267
  _globals['_EMPTY']._serialized_start=45
  _globals['_EMPTY']._serialized_end=52
  _globals['_CONFIGURATION']._serialized_start=54
  _globals['_CONFIGURATION']._serialized_end=119
  _globals['_STATUS']._serialized_start=121
  _globals['_STATUS']._serialized_end=193
  _globals['_TRAFFICSNIFFER']._serialized_start=270
  _globals['_TRAFFICSNIFFER']._serialized_end=649
# @@protoc_insertion_point(module_scope)
