# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import traffic_sniffer_pb2 as traffic__sniffer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in traffic_sniffer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrafficSnifferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/traffic.sniffer.v1.TrafficSniffer/Configure',
                request_serializer=traffic__sniffer__pb2.Configuration.SerializeToString,
                response_deserializer=traffic__sniffer__pb2.Configuration.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/traffic.sniffer.v1.TrafficSniffer/GetConfig',
                request_serializer=traffic__sniffer__pb2.Empty.SerializeToString,
                response_deserializer=traffic__sniffer__pb2.Configuration.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/traffic.sniffer.v1.TrafficSniffer/Start',
                request_serializer=traffic__sniffer__pb2.Empty.SerializeToString,
                response_deserializer=traffic__sniffer__pb2.Status.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/traffic.sniffer.v1.TrafficSniffer/Stop',
                request_serializer=traffic__sniffer__pb2.Empty.SerializeToString,
                response_deserializer=traffic__sniffer__pb2.Status.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/traffic.sniffer.v1.TrafficSniffer/GetStatus',
                request_serializer=traffic__sniffer__pb2.Empty.SerializeToString,
                response_deserializer=traffic__sniffer__pb2.Status.FromString,
                _registered_method=True)


class TrafficSnifferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrafficSnifferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=traffic__sniffer__pb2.Configuration.FromString,
                    response_serializer=traffic__sniffer__pb2.Configuration.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=traffic__sniffer__pb2.Empty.FromString,
                    response_serializer=traffic__sniffer__pb2.Configuration.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=traffic__sniffer__pb2.Empty.FromString,
                    response_serializer=traffic__sniffer__pb2.Status.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=traffic__sniffer__pb2.Empty.FromString,
                    response_serializer=traffic__sniffer__pb2.Status.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=traffic__sniffer__pb2.Empty.FromString,
                    response_serializer=traffic__sniffer__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'traffic.sniffer.v1.TrafficSniffer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('traffic.sniffer.v1.TrafficSniffer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrafficSniffer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/traffic.sniffer.v1.TrafficSniffer/Configure',
            traffic__sniffer__pb2.Configuration.SerializeToString,
            traffic__sniffer__pb2.Configuration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/traffic.sniffer.v1.TrafficSniffer/GetConfig',
            traffic__sniffer__pb2.Empty.SerializeToString,
            traffic__sniffer__pb2.Configuration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/traffic.sniffer.v1.TrafficSniffer/Start',
            traffic__sniffer__pb2.Empty.SerializeToString,
            traffic__sniffer__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/traffic.sniffer.v1.TrafficSniffer/Stop',
            traffic__sniffer__pb2.Empty.SerializeToString,
            traffic__sniffer__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/traffic.sniffer.v1.TrafficSniffer/GetStatus',
            traffic__sniffer__pb2.Empty.SerializeToString,
            traffic__sniffer__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
